# Generated by Django 5.0.4 on 2024-04-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_emails_delete_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="emails",
            name="isfishing",
            field=models.BooleanField(default=False),
        ),
    ]
